development:
  adapter: mysql2
  encoding: utf8
  database: ninetofive_development
  username: root
  password:
  # socket: /opt/lampp/var/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: ninetofive_test
  username: root
  password:
  # socket: /opt/lampp/var/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: ninetofive_production
  username: root
  password:
  # socket: /opt/lampp/var/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

  # adapter: sqlite3
  # database: db/production.sqlite3
  # pool: 5
  # timeout: 5000

